<a href="https://colab.research.google.com/github/edik06031-rgb/DTA_2026/blob/main/HW/Pandas_practice_120.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🐼 Pandas: практикум на 120 завдань

**Тренування синтаксису • рівень: простий**

---

Цей зошит містить **120 коротких завдань** на той функціонал pandas, який ми розглянули на лекції. Мета — набити руку на синтаксисі, щоб команди стали автоматичними.

## Дані
Працюємо з даними онлайн-книгарні — файл `bookstore_sales.csv` (400 замовлень за 8 місяців).

| Стовпець | Опис |
|---|---|
| `order_id` | Номер замовлення |
| `date` | Дата замовлення |
| `city` | Місто покупця |
| `book_title` | Назва книги |
| `genre` | Жанр |
| `unit_price` | Ціна за одну книгу (грн) |
| `quantity` | Кількість книг |
| `discount_pct` | Знижка у відсотках |
| `total` | Підсумкова сума замовлення (грн) |
| `channel` | Канал замовлення (Сайт / Застосунок / Телефон) |
| `manager` | Менеджер, що оформив замовлення |
| `rating` | Оцінка покупця (3-5) |

## Як працювати
- Запускайте кожну комірку (Shift + Enter)
- Якщо забули синтаксис — підгляньте в notebook з лекції
- Не бійтесь помилок, експериментуйте!

---

## Підготовка

Спочатку запустіть цю комірку — вона імпортує pandas і завантажує дані. Усі завдання працюють зі змінною `df`.

In [ ]:
import pandas as pd

df = pd.read_csv("bookstore_sales.csv")
df.head()

,order_id,date,city,book_title,genre,unit_price,quantity,discount_pct,total,channel,manager,rating
0,5275,2024-06-25,Харків,Sapiens,Наука,410,2,0,820.0,Телефон,Ірина,5
1,5386,2024-08-09,Одеса,Гордість і упередження,Романтика,240,2,0,480.0,Телефон,Ірина,5
2,5100,2024-02-21,Харків,Гордість і упередження,Романтика,240,1,15,204.0,Сайт,Ірина,5
3,5352,2024-08-18,Дніпро,Sapiens,Наука,410,1,0,410.0,Мобільний застосунок,Віктор,3
4,5032,2024-01-27,Київ,Шерлок Холмс,Детектив,250,1,20,200.0,Сайт,Олег,3

## Розділ 1. Перший погляд на дані (завдання 1-15)

Команди: `head()`, `tail()`, `shape`, `columns`, `info()`, `describe()`, `dtypes`.

**Завдання 1.** Виведіть перші 5 рядків таблиці.

In [ ]:
# Завдання 1:
df.head()

,order_id,date,city,book_title,genre,unit_price,quantity,discount_pct,total,channel,manager,rating
0,5275,2024-06-25,Харків,Sapiens,Наука,410,2,0,820.0,Телефон,Ірина,5
1,5386,2024-08-09,Одеса,Гордість і упередження,Романтика,240,2,0,480.0,Телефон,Ірина,5
2,5100,2024-02-21,Харків,Гордість і упередження,Романтика,240,1,15,204.0,Сайт,Ірина,5
3,5352,2024-08-18,Дніпро,Sapiens,Наука,410,1,0,410.0,Мобільний застосунок,Віктор,3
4,5032,2024-01-27,Київ,Шерлок Холмс,Детектив,250,1,20,200.0,Сайт,Олег,3

**Завдання 2.** Виведіть перші 10 рядків таблиці.

> 💡 head() приймає число — скільки рядків показати.

In [ ]:
# Завдання 2:
df.head(10)

,order_id,date,city,book_title,genre,unit_price,quantity,discount_pct,total,channel,manager,rating
0,5275,2024-06-25,Харків,Sapiens,Наука,410,2,0,820.0,Телефон,Ірина,5
1,5386,2024-08-09,Одеса,Гордість і упередження,Романтика,240,2,0,480.0,Телефон,Ірина,5
2,5100,2024-02-21,Харків,Гордість і упередження,Романтика,240,1,15,204.0,Сайт,Ірина,5
3,5352,2024-08-18,Дніпро,Sapiens,Наука,410,1,0,410.0,Мобільний застосунок,Віктор,3
4,5032,2024-01-27,Київ,Шерлок Холмс,Детектив,250,1,20,200.0,Сайт,Олег,3
5,5137,2024-03-06,Харків,Маленький принц,Дитяча,160,2,0,320.0,Телефон,Олег,3
6,5022,2024-01-24,Київ,Лісова пісня,Поезія,150,2,0,300.0,Телефон,Олег,4
7,5139,2024-03-22,Київ,Лісова пісня,Поезія,150,3,10,405.0,Мобільний застосунок,Наталя,4
8,5104,2024-03-13,Харків,Квантова фізика,Наука,450,2,5,855.0,Мобільний застосунок,Софія,4
9,5184,2024-04-24,Львів,Кобзар,Поезія,180,1,0,180.0,Мобільний застосунок,Софія,4

**Завдання 3.** Виведіть останні 5 рядків таблиці.

> 💡 Скористайтесь методом tail().

In [ ]:
# Завдання 3:
df.tail()

,order_id,date,city,book_title,genre,unit_price,quantity,discount_pct,total,channel,manager,rating
395,5043,2024-01-22,Львів,Дюна,Фантастика,320,2,0,640.0,Мобільний застосунок,Ірина,3
396,5129,2024-03-21,Харків,Sapiens,Наука,410,5,5,1947.5,Сайт,Олег,5
397,5185,2024-04-22,Київ,Війна і мир,Історія,380,1,0,380.0,Мобільний застосунок,Ірина,5
398,5336,2024-07-26,Львів,Гордість і упередження,Романтика,240,3,0,720.0,Сайт,Ірина,5
399,5048,2024-01-14,Одеса,Сила звички,Бізнес,260,1,0,260.0,Мобільний застосунок,Ірина,3

**Завдання 4.** Виведіть останні 3 рядки таблиці.

In [ ]:
# Завдання 4:
df.tail(3)

,order_id,date,city,book_title,genre,unit_price,quantity,discount_pct,total,channel,manager,rating
397,5185,2024-04-22,Київ,Війна і мир,Історія,380,1,0,380.0,Мобільний застосунок,Ірина,5
398,5336,2024-07-26,Львів,Гордість і упередження,Романтика,240,3,0,720.0,Сайт,Ірина,5
399,5048,2024-01-14,Одеса,Сила звички,Бізнес,260,1,0,260.0,Мобільний застосунок,Ірина,3

**Завдання 5.** Дізнайтесь розмір таблиці (кількість рядків і стовпців).

> 💡 Атрибут shape.

In [ ]:
# Завдання 5:
df.shape

(400, 12)

**Завдання 6.** Виведіть тільки кількість рядків у таблиці.

> 💡 shape[0] повертає перше число.

In [ ]:
# Завдання 6:
df.shape[0]

400

**Завдання 7.** Виведіть тільки кількість стовпців у таблиці.

> 💡 shape[1].

In [ ]:
# Завдання 7:
df.shape[1]

12

**Завдання 8.** Виведіть назви всіх стовпців.

> 💡 Атрибут columns.

In [ ]:
# Завдання 8:
df.columns

Index(['order_id', 'date', 'city', 'book_title', 'genre', 'unit_price',
       'quantity', 'discount_pct', 'total', 'channel', 'manager', 'rating'],
      dtype='object')

**Завдання 9.** Виведіть загальну інформацію про таблицю (типи даних, кількість значень).

> 💡 Метод info().

In [ ]:
# Завдання 9:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      400 non-null    int64
 1   date          400 non-null    object
 2   city          400 non-null    object
 3   book_title    400 non-null    object
 4   genre         400 non-null    object
 5   unit_price    400 non-null    int64
 6   quantity      400 non-null    int64
 7   discount_pct  400 non-null    int64
 8   total         400 non-null    float64
 9   channel       400 non-null    object
 10  manager       400 non-null    object
 11  rating        400 non-null    int64
dtypes: float64(1), int64(5), object(6)
memory usage: 37.6+ KB

**Завдання 10.** Виведіть статистику по числових стовпцях (середнє, мін, макс тощо).

> 💡 Метод describe().

In [ ]:
# Завдання 10:
df.describe()

,order_id,unit_price,quantity,discount_pct,total,rating
count,400.000000,400.000000,400.00000,400.000000,400.000000,400.000000
mean,5200.500000,283.350000,2.05750,2.500000,572.005000,4.255000
std,115.614301,86.900268,1.16945,5.142091,398.019126,0.707975
min,5001.000000,150.000000,1.00000,0.000000,128.000000,3.000000
25%,5100.750000,220.000000,1.00000,0.000000,289.500000,4.000000
50%,5200.500000,270.000000,2.00000,0.000000,450.000000,4.000000
75%,5300.250000,350.000000,3.00000,0.000000,765.000000,5.000000
max,5400.000000,450.000000,5.00000,20.000000,2250.000000,5.000000

**Завдання 11.** Виведіть типи даних кожного стовпця.

> 💡 Атрибут dtypes.

In [ ]:
# Завдання 11:
df.dtypes

order_id          int64
date             object
city             object
book_title       object
genre            object
unit_price        int64
quantity          int64
discount_pct      int64
total           float64
channel          object
manager          object
rating            int64
dtype: object

**Завдання 12.** Виведіть перші 7 рядків таблиці.

In [ ]:
# Завдання 12:
df.head(7)

,order_id,date,city,book_title,genre,unit_price,quantity,discount_pct,total,channel,manager,rating
0,5275,2024-06-25,Харків,Sapiens,Наука,410,2,0,820.0,Телефон,Ірина,5
1,5386,2024-08-09,Одеса,Гордість і упередження,Романтика,240,2,0,480.0,Телефон,Ірина,5
2,5100,2024-02-21,Харків,Гордість і упередження,Романтика,240,1,15,204.0,Сайт,Ірина,5
3,5352,2024-08-18,Дніпро,Sapiens,Наука,410,1,0,410.0,Мобільний застосунок,Віктор,3
4,5032,2024-01-27,Київ,Шерлок Холмс,Детектив,250,1,20,200.0,Сайт,Олег,3
5,5137,2024-03-06,Харків,Маленький принц,Дитяча,160,2,0,320.0,Телефон,Олег,3
6,5022,2024-01-24,Київ,Лісова пісня,Поезія,150,2,0,300.0,Телефон,Олег,4

**Завдання 13.** Виведіть останні 10 рядків таблиці.

In [ ]:
# Завдання 13:
df.tail(13)

,order_id,date,city,book_title,genre,unit_price,quantity,discount_pct,total,channel,manager,rating
387,5157,2024-04-04,Харків,Дюна,Фантастика,320,1,0,320.0,Сайт,Олег,5
388,5321,2024-07-09,Дніпро,Гордість і упередження,Романтика,240,2,0,480.0,Телефон,Ірина,4
389,5203,2024-05-21,Харків,Кладовище домашніх тварин,Детектив,270,1,0,270.0,Сайт,Софія,5
390,5027,2024-01-17,Харків,Лісова пісня,Поезія,150,1,0,150.0,Сайт,Софія,4
391,5085,2024-02-08,Одеса,Шерлок Холмс,Детектив,250,2,5,475.0,Телефон,Софія,3
392,5333,2024-07-05,Дніпро,Сила звички,Бізнес,260,2,0,520.0,Мобільний застосунок,Наталя,3
393,5341,2024-07-17,Львів,Маленький принц,Дитяча,160,5,20,640.0,Сайт,Софія,5
394,5191,2024-04-05,Львів,Війна і мир,Історія,380,4,0,1520.0,Мобільний застосунок,Олег,4
395,5043,2024-01-22,Львів,Дюна,Фантастика,320,2,0,640.0,Мобільний застосунок,Ірина,3
396,5129,2024-03-21,Харків,Sapiens,Наука,410,5,5,1947.5,Сайт,Олег,5
397,5185,2024-04-22,Київ,Війна і мир,Історія,380,1,0,380.0,Мобільний застосунок,Ірина,5
398,5336,2024-07-26,Львів,Гордість і упередження,Романтика,240,3,0,720.0,Сайт,Ірина,5
399,5048,2024-01-14,Одеса,Сила звички,Бізнес,260,1,0,260.0,Мобільний застосунок,Ірина,3

**Завдання 14.** Скільки всього значень (рядків) у таблиці? Використайте функцію len().

In [ ]:
# Завдання 14:
len(df)

400

**Завдання 15.** Виведіть перший рядок таблиці.

> 💡 head(1).

In [ ]:
# Завдання 15:
df.head(1)

,order_id,date,city,book_title,genre,unit_price,quantity,discount_pct,total,channel,manager,rating
0,5275,2024-06-25,Харків,Sapiens,Наука,410,2,0,820.0,Телефон,Ірина,5

## Розділ 2. Вибір стовпців (завдання 16-30)

Вибір одного стовпця: `df["col"]`. Вибір кількох: `df[["col1", "col2"]]`.

**Завдання 16.** Виведіть стовпець `city`.

In [ ]:
# Завдання 16:
df["city"]

0      Харків
1       Одеса
2      Харків
3      Дніпро
4        Київ
        ...
395     Львів
396    Харків
397      Київ
398     Львів
399     Одеса
Name: city, Length: 400, dtype: object

**Завдання 17.** Виведіть стовпець `total`.

In [ ]:
# Завдання 17:
df["total"]

0       820.0
1       480.0
2       204.0
3       410.0
4       200.0
        ...
395     640.0
396    1947.5
397     380.0
398     720.0
399     260.0
Name: total, Length: 400, dtype: float64

**Завдання 18.** Виведіть стовпець `book_title`.

In [ ]:
# Завдання 18:
df['book_title']

0                     Sapiens
1      Гордість і упередження
2      Гордість і упередження
3                     Sapiens
4                Шерлок Холмс
                ...
395                      Дюна
396                   Sapiens
397               Війна і мир
398    Гордість і упередження
399               Сила звички
Name: book_title, Length: 400, dtype: object

**Завдання 19.** Виведіть стовпці `city` та `total` разом.

> 💡 Подвійні дужки: df[["city", "total"]].

In [ ]:
# Завдання 19:
df[["city", "total"]]

       city   total
0    Харків   820.0
1     Одеса   480.0
2    Харків   204.0
3    Дніпро   410.0
4      Київ   200.0
..      ...     ...
395   Львів   640.0
396  Харків  1947.5
397    Київ   380.0
398   Львів   720.0
399   Одеса   260.0

[400 rows x 2 columns]

**Завдання 20.** Виведіть стовпці `book_title`, `genre` та `unit_price`.

In [ ]:
# Завдання 20:
df[['book_title','genre','unit_price']]

                 book_title       genre  unit_price
0                   Sapiens       Наука         410
1    Гордість і упередження   Романтика         240
2    Гордість і упередження   Романтика         240
3                   Sapiens       Наука         410
4              Шерлок Холмс    Детектив         250
..                      ...         ...         ...
395                    Дюна  Фантастика         320
396                 Sapiens       Наука         410
397             Війна і мир     Історія         380
398  Гордість і упередження   Романтика         240
399             Сила звички      Бізнес         260

[400 rows x 3 columns]

**Завдання 21.** Виведіть перші 5 рядків стовпця `genre`.

> 💡 Можна поєднати: df["genre"].head().

In [ ]:
# Завдання 21:
df["genre"].head()

0        Наука
1    Романтика
2    Романтика
3        Наука
4     Детектив
Name: genre, dtype: object

**Завдання 22.** Виведіть стовпці `manager` та `total`, лише перші 10 рядків.

In [ ]:
# Завдання 22:
df[['manager', 'total']]. head(10)

  manager  total
0   Ірина  820.0
1   Ірина  480.0
2   Ірина  204.0
3  Віктор  410.0
4    Олег  200.0
5    Олег  320.0
6    Олег  300.0
7  Наталя  405.0
8   Софія  855.0
9   Софія  180.0

**Завдання 23.** Виведіть стовпець `rating`.

In [ ]:
# Завдання 23:
df['rating']

0      5
1      5
2      5
3      3
4      3
      ..
395    3
396    5
397    5
398    5
399    3
Name: rating, Length: 400, dtype: int64

**Завдання 24.** Виведіть стовпці `order_id`, `date` та `city`.

In [ ]:
# Завдання 24:
df[['order_id','date','city']]

     order_id        date    city
0        5275  2024-06-25  Харків
1        5386  2024-08-09   Одеса
2        5100  2024-02-21  Харків
3        5352  2024-08-18  Дніпро
4        5032  2024-01-27    Київ
..        ...         ...     ...
395      5043  2024-01-22   Львів
396      5129  2024-03-21  Харків
397      5185  2024-04-22    Київ
398      5336  2024-07-26   Львів
399      5048  2024-01-14   Одеса

[400 rows x 3 columns]

**Завдання 25.** Виведіть перші 3 рядки стовпців `book_title` та `quantity`.

In [ ]:
# Завдання 25:
df[['book_title','quantity']].head(3)

               book_title  quantity
0                 Sapiens         2
1  Гордість і упередження         2
2  Гордість і упередження         1

**Завдання 26.** Виведіть стовпець `channel`.

In [ ]:
# Завдання 26:
df['channel']

0                   Телефон
1                   Телефон
2                      Сайт
3      Мобільний застосунок
4                      Сайт
               ...
395    Мобільний застосунок
396                    Сайт
397    Мобільний застосунок
398                    Сайт
399    Мобільний застосунок
Name: channel, Length: 400, dtype: object

**Завдання 27.** Виведіть стовпці `city`, `genre` та `total`, останні 5 рядків.

> 💡 Поєднайте подвійні дужки і tail().

In [ ]:
# Завдання 27:
df[['city','genre','total']].tail()

       city       genre   total
395   Львів  Фантастика   640.0
396  Харків       Наука  1947.5
397    Київ     Історія   380.0
398   Львів   Романтика   720.0
399   Одеса      Бізнес   260.0

**Завдання 28.** Виведіть стовпець `discount_pct`.

In [ ]:
# Завдання 28:
df.discount_pct

0       0
1       0
2      15
3       0
4      20
       ..
395     0
396     5
397     0
398     0
399     0
Name: discount_pct, Length: 400, dtype: int64

**Завдання 29.** Виведіть стовпці `unit_price` та `quantity`.

In [ ]:
# Завдання 29:
df[['unit_price','quantity']]

     unit_price  quantity
0           410         2
1           240         2
2           240         1
3           410         1
4           250         1
..          ...       ...
395         320         2
396         410         5
397         380         1
398         240         3
399         260         1

[400 rows x 2 columns]

**Завдання 30.** Виведіть стовпець `quantity`, перші 8 рядків.

In [ ]:
# Завдання 30:
df['quantity'].head(8)

0    2
1    2
2    1
3    1
4    1
5    2
6    2
7    3
Name: quantity, dtype: int64

## Розділ 3. Базові агрегати по стовпцю (завдання 31-50)

Команди: `sum()`, `mean()`, `max()`, `min()`, `count()`, `unique()`, `nunique()`, `value_counts()`.

**Завдання 31.** Порахуйте загальну суму всіх замовлень (стовпець `total`).

> 💡 df["total"].sum().

In [ ]:
# Завдання 31:
#df["total"].sum()
total_sales = df["total"].sum()

print('Cумa всіх замовлень:',total_sales)

Cумa всіх замовлень: 228802.0

**Завдання 32.** Порахуйте середню суму замовлення.

> 💡 mean().

In [ ]:
# Завдання 32:
avg_quantity_sum = df["total"].mean()
print('середня сума замовлення:'),avg_quantity_sum

середня сума замовлення:

(None, np.float64(572.005))

**Завдання 33.** Знайдіть максимальну суму замовлення.

> 💡 max().

In [ ]:
# Завдання 33:
max_sum = df["total"].max()
print("максимальнa сумa замовлення: "),max_sum

максимальнa сумa замовлення:

(None, 2250.0)

**Завдання 34.** Знайдіть мінімальну суму замовлення.

> 💡 min().

In [ ]:
# Завдання 34:
min_sum = df["total"].min()
print("мінімальнa сумa замовлення :"),min_sum

мінімальнa сумa замовлення :

(None, 128.0)

**Завдання 35.** Порахуйте, скільки всього замовлень (використайте count() на будь-якому стовпці).

In [ ]:
# Завдання 35:
orders_count = df["total"].count()

print(" всього замовлень :",orders_count)

 всього замовлень : 400

**Завдання 36.** Знайдіть середню ціну книги (`unit_price`).

In [ ]:
# Завдання 36:
df["unit_price"].mean()

np.float64(283.35)

**Завдання 37.** Знайдіть максимальну кількість книг у одному замовленні (`quantity`).

In [ ]:
# Завдання 37:
df["quantity"].max()

5

**Завдання 38.** Порахуйте загальну кількість проданих книг (сума стовпця `quantity`).

In [ ]:
# Завдання 38:
total_quantity = df['quantity'].sum()
print(total_quantity)

823

**Завдання 39.** Виведіть усі унікальні міста.

> 💡 Метод unique().

In [ ]:
# Завдання 39:
df['city'].unique()

array(['Харків', 'Одеса', 'Дніпро', 'Київ', 'Львів'], dtype=object)

**Завдання 40.** Виведіть усі унікальні жанри.

In [ ]:
# Завдання 40:
df['genre'].unique()

array(['Наука', 'Романтика', 'Детектив', 'Дитяча', 'Поезія', 'Бізнес',
       'Історія', 'Фантастика'], dtype=object)

**Завдання 41.** Скільки унікальних міст у даних?

> 💡 Метод nunique().

In [ ]:
# Завдання 41:
df.nunique()

order_id        400
date            198
city              5
book_title       15
genre             8
unit_price       15
quantity          5
discount_pct      5
total           127
channel           3
manager           5
rating            3
dtype: int64

**Завдання 42.** Скільки унікальних книг у даних?

In [ ]:
# Завдання 42:
df["book_title"].unique()

array(['Sapiens', 'Гордість і упередження', 'Шерлок Холмс',
       'Маленький принц', 'Лісова пісня', 'Квантова фізика', 'Кобзар',
       'Сила звички', 'Війна і мир', 'Тіні забутих предків', 'Дюна',
       '1984', 'Атомні звички', 'Кладовище домашніх тварин',
       'Гаррі Поттер'], dtype=object)

**Завдання 43.** Скільки унікальних жанрів у даних?

In [ ]:
# Завдання 43:
df["genre"].unique()

array(['Наука', 'Романтика', 'Детектив', 'Дитяча', 'Поезія', 'Бізнес',
       'Історія', 'Фантастика'], dtype=object)

**Завдання 44.** Скільки замовлень з кожного міста? Використайте value_counts().

> 💡 df["city"].value_counts().

In [ ]:
# Завдання 44:
df["city"].value_counts()

city
Харків    98
Львів     83
Одеса     82
Дніпро    69
Київ      68
Name: count, dtype: int64

**Завдання 45.** Скільки замовлень у кожному жанрі?

> 💡 value_counts() на стовпці genre.

In [ ]:
# Завдання 45:
df["genre"].value_counts()

genre
Наука         61
Бізнес        59
Історія       52
Поезія        51
Фантастика    49
Детектив      47
Дитяча        47
Романтика     34
Name: count, dtype: int64

**Завдання 46.** Скільки замовлень оформив кожен менеджер?

In [ ]:
# Завдання 46:
df.groupby("manager")["order_id"].count()

manager
Ірина     77
Віктор    75
Наталя    79
Олег      80
Софія     89
Name: order_id, dtype: int64

**Завдання 47.** Скільки замовлень через кожен канал (`channel`)?

In [ ]:
# Завдання 47:
df.groupby("channel")["order_id"].count()

channel
Мобільний застосунок    135
Сайт                    124
Телефон                 141
Name: order_id, dtype: int64

**Завдання 48.** Виведіть усі унікальні значення оцінок (`rating`).

In [ ]:
# Завдання 48:
df["rating"].unique()

array([5, 3, 4])

**Завдання 49.** Знайдіть середню оцінку (`rating`).

In [ ]:
# Завдання 49:
#df["rating"].mean()
round(df["rating"].mean(), 1)

np.float64(4.3)

**Завдання 50.** Знайдіть середню знижку (`discount_pct`).

In [ ]:
# Завдання 50:
round(df["discount_pct"].mean(), 1)

np.float64(2.5)

## Розділ 4. Фільтрація — одна умова (завдання 51-70)

Принцип: `df[df["стовпець"] умова]`. Наприклад, `df[df["total"] > 500]`.

**Завдання 51.** Виведіть усі замовлення з міста Київ.

> 💡 df[df["city"] == "Київ"].

In [ ]:
# Завдання 51:
df[df["city"] == "Київ"]

,order_id,date,city,book_title,genre,unit_price,quantity,discount_pct,total,channel,manager,rating
4,5032,2024-01-27,Київ,Шерлок Холмс,Детектив,250,1,20,200.0,Сайт,Олег,3
6,5022,2024-01-24,Київ,Лісова пісня,Поезія,150,2,0,300.0,Телефон,Олег,4
7,5139,2024-03-22,Київ,Лісова пісня,Поезія,150,3,10,405.0,Мобільний застосунок,Наталя,4
14,5295,2024-06-12,Київ,Війна і мир,Історія,380,2,0,760.0,Телефон,Ірина,5
16,5102,2024-03-03,Київ,Шерлок Холмс,Детектив,250,3,0,750.0,Сайт,Олег,5
...,...,...,...,...,...,...,...,...,...,...,...,...
375,5040,2024-01-25,Київ,Кладовище домашніх тварин,Детектив,270,2,0,540.0,Мобільний застосунок,Софія,5
376,5245,2024-05-18,Київ,Гордість і упередження,Романтика,240,2,0,480.0,Сайт,Наталя,3
378,5001,2024-01-08,Київ,Кладовище домашніх тварин,Детектив,270,1,0,270.0,Телефон,Софія,4
384,5120,2024-03-23,Київ,Гордість і упередження,Романтика,240,1,0,240.0,Телефон,Софія,4
397,5185,2024-04-22,Київ,Війна і мир,Історія,380,1,0,380.0,Мобільний застосунок,Ірина,5

**Завдання 52.** Виведіть усі замовлення з міста Львів.

In [ ]:
# Завдання 52:
df[df["city"]== "Львів"]

,order_id,date,city,book_title,genre,unit_price,quantity,discount_pct,total,channel,manager,rating
9,5184,2024-04-24,Львів,Кобзар,Поезія,180,1,0,180.0,Мобільний застосунок,Софія,4
10,5208,2024-05-13,Львів,Лісова пісня,Поезія,150,3,0,450.0,Телефон,Софія,4
31,5297,2024-06-20,Львів,Кладовище домашніх тварин,Детектив,270,4,0,1080.0,Мобільний застосунок,Олег,4
34,5158,2024-04-02,Львів,Кладовище домашніх тварин,Детектив,270,2,20,432.0,Сайт,Софія,5
46,5373,2024-08-08,Львів,Атомні звички,Бізнес,290,2,15,493.0,Сайт,Віктор,5
...,...,...,...,...,...,...,...,...,...,...,...,...
386,5372,2024-08-24,Львів,Кладовище домашніх тварин,Детектив,270,3,15,688.5,Телефон,Олег,4
393,5341,2024-07-17,Львів,Маленький принц,Дитяча,160,5,20,640.0,Сайт,Софія,5
394,5191,2024-04-05,Львів,Війна і мир,Історія,380,4,0,1520.0,Мобільний застосунок,Олег,4
395,5043,2024-01-22,Львів,Дюна,Фантастика,320,2,0,640.0,Мобільний застосунок,Ірина,3
398,5336,2024-07-26,Львів,Гордість і упередження,Романтика,240,3,0,720.0,Сайт,Ірина,5

**Завдання 53.** Виведіть усі замовлення з міста Одеса.

In [ ]:
# Завдання 53:
df[df["city"]== "Одеса"]

,order_id,date,city,book_title,genre,unit_price,quantity,discount_pct,total,channel,manager,rating
1,5386,2024-08-09,Одеса,Гордість і упередження,Романтика,240,2,0,480.0,Телефон,Ірина,5
11,5114,2024-03-21,Одеса,Квантова фізика,Наука,450,3,0,1350.0,Сайт,Софія,4
15,5325,2024-07-15,Одеса,Гордість і упередження,Романтика,240,1,0,240.0,Мобільний застосунок,Наталя,4
18,5269,2024-06-20,Одеса,Лісова пісня,Поезія,150,2,0,300.0,Телефон,Наталя,5
21,5194,2024-04-21,Одеса,1984,Фантастика,280,1,0,280.0,Телефон,Ірина,4
...,...,...,...,...,...,...,...,...,...,...,...,...
371,5266,2024-06-12,Одеса,Шерлок Холмс,Детектив,250,1,0,250.0,Телефон,Наталя,5
372,5116,2024-03-14,Одеса,Кладовище домашніх тварин,Детектив,270,1,0,270.0,Телефон,Віктор,5
377,5110,2024-03-27,Одеса,1984,Фантастика,280,3,0,840.0,Мобільний застосунок,Ірина,5
391,5085,2024-02-08,Одеса,Шерлок Холмс,Детектив,250,2,5,475.0,Телефон,Софія,3
399,5048,2024-01-14,Одеса,Сила звички,Бізнес,260,1,0,260.0,Мобільний застосунок,Ірина,3

**Завдання 54.** Виведіть усі замовлення жанру `Фантастика`.

In [ ]:
# Завдання 54:
df[df["genre"]== "Фантастика"]

,order_id,date,city,book_title,genre,unit_price,quantity,discount_pct,total,channel,manager,rating
20,5165,2024-04-14,Харків,Дюна,Фантастика,320,5,10,1440.0,Телефон,Віктор,5
21,5194,2024-04-21,Одеса,1984,Фантастика,280,1,0,280.0,Телефон,Ірина,4
33,5288,2024-06-10,Київ,1984,Фантастика,280,4,15,952.0,Мобільний застосунок,Софія,5
37,5382,2024-08-02,Київ,1984,Фантастика,280,1,0,280.0,Мобільний застосунок,Олег,5
43,5346,2024-07-03,Дніпро,Дюна,Фантастика,320,1,0,320.0,Телефон,Віктор,4
50,5164,2024-04-22,Харків,Дюна,Фантастика,320,2,10,576.0,Телефон,Ірина,4
59,5294,2024-06-25,Одеса,Дюна,Фантастика,320,1,0,320.0,Мобільний застосунок,Софія,4
70,5153,2024-04-04,Дніпро,Дюна,Фантастика,320,1,0,320.0,Сайт,Віктор,4
75,5344,2024-07-28,Дніпро,1984,Фантастика,280,2,0,560.0,Мобільний застосунок,Віктор,4
76,5283,2024-06-08,Дніпро,1984,Фантастика,280,1,0,280.0,Сайт,Олег,4
78,5390,2024-08-26,Одеса,1984,Фантастика,280,3,5,798.0,Телефон,Наталя,3
92,5400,2024-08-23,Одеса,Дюна,Фантастика,320,5,0,1600.0,Сайт,Наталя,5
123,5234,2024-05-02,Одеса,1984,Фантастика,280,2,0,560.0,Телефон,Віктор,5
124,5343,2024-07-07,Харків,1984,Фантастика,280,4,0,1120.0,Сайт,Наталя,5
131,5051,2024-02-14,Львів,1984,Фантастика,280,3,0,840.0,Мобільний застосунок,Олег,5
136,5334,2024-07-20,Харків,Дюна,Фантастика,320,2,0,640.0,Сайт,Ірина,5
139,5353,2024-08-03,Дніпро,Дюна,Фантастика,320,1,0,320.0,Сайт,Софія,5
143,5247,2024-05-15,Дніпро,1984,Фантастика,280,5,0,1400.0,Мобільний застосунок,Олег,4
147,5385,2024-08-06,Дніпро,Дюна,Фантастика,320,1,0,320.0,Телефон,Віктор,5
148,5018,2024-01-24,Дніпро,1984,Фантастика,280,2,15,476.0,Сайт,Софія,4
156,5221,2024-05-23,Харків,Дюна,Фантастика,320,2,0,640.0,Сайт,Софія,3
161,5082,2024-02-04,Львів,1984,Фантастика,280,1,0,280.0,Мобільний застосунок,Наталя,5
214,5192,2024-04-21,Харків,1984,Фантастика,280,2,5,532.0,Мобільний застосунок,Софія,3
218,5067,2024-02-15,Львів,1984,Фантастика,280,3,0,840.0,Сайт,Віктор,3
238,5274,2024-06-07,Одеса,Дюна,Фантастика,320,2,0,640.0,Мобільний застосунок,Олег,3
243,5030,2024-01-28,Львів,Дюна,Фантастика,320,1,0,320.0,Сайт,Софія,3
245,5237,2024-05-21,Харків,Дюна,Фантастика,320,1,0,320.0,Телефон,Ірина,4
246,5023,2024-01-06,Дніпро,1984,Фантастика,280,2,15,476.0,Мобільний застосунок,Олег,4
267,5396,2024-08-03,Харків,Дюна,Фантастика,320,3,10,864.0,Телефон,Наталя,5
271,5257,2024-06-24,Одеса,1984,Фантастика,280,1,0,280.0,Мобільний застосунок,Олег,5
279,5008,2024-01-03,Київ,Дюна,Фантастика,320,2,5,608.0,Мобільний застосунок,Наталя,5
280,5035,2024-01-02,Дніпро,1984,Фантастика,280,1,0,280.0,Сайт,Наталя,5
283,5242,2024-05-03,Одеса,1984,Фантастика,280,4,0,1120.0,Телефон,Наталя,5
296,5124,2024-03-17,Львів,1984,Фантастика,280,1,15,238.0,Сайт,Наталя,5
301,5028,2024-01-19,Харків,1984,Фантастика,280,2,10,504.0,Мобільний застосунок,Олег,4
303,5201,2024-05-03,Дніпро,Дюна,Фантастика,320,3,0,960.0,Телефон,Віктор,4
311,5312,2024-07-28,Київ,Дюна,Фантастика,320,1,0,320.0,Мобільний застосунок,Віктор,3
314,5284,2024-06-16,Львів,Дюна,Фантастика,320,1,0,320.0,Сайт,Софія,3
317,5142,2024-03-09,Київ,Дюна,Фантастика,320,5,0,1600.0,Телефон,Віктор,3
326,5072,2024-02-05,Київ,1984,Фантастика,280,1,0,280.0,Мобільний застосунок,Віктор,5
344,5036,2024-01-28,Київ,Дюна,Фантастика,320,1,0,320.0,Телефон,Ірина,4
354,5363,2024-08-22,Харків,1984,Фантастика,280,2,0,560.0,Мобільний застосунок,Ірина,4
366,5357,2024-08-20,Одеса,Дюна,Фантастика,320,4,0,1280.0,Мобільний застосунок,Наталя,4
367,5369,2024-08-03,Львів,Дюна,Фантастика,320,2,0,640.0,Мобільний застосунок,Наталя,3
374,5068,2024-02-18,Харків,1984,Фантастика,280,3,0,840.0,Телефон,Софія,5
377,5110,2024-03-27,Одеса,1984,Фантастика,280,3,0,840.0,Мобільний застосунок,Ірина,5
382,5399,2024-08-15,Львів,Дюна,Фантастика,320,1,5,304.0,Мобільний застосунок,Віктор,3
387,5157,2024-04-04,Харків,Дюна,Фантастика,320,1,0,320.0,Сайт,Олег,5
395,5043,2024-01-22,Львів,Дюна,Фантастика,320,2,0,640.0,Мобільний застосунок,Ірина,3

**Завдання 55.** Виведіть усі замовлення жанру `Детектив`.

In [ ]:
# Завдання 55:
df[df["genre"]== "Детектив"]

,order_id,date,city,book_title,genre,unit_price,quantity,discount_pct,total,channel,manager,rating
4,5032,2024-01-27,Київ,Шерлок Холмс,Детектив,250,1,20,200.0,Сайт,Олег,3
16,5102,2024-03-03,Київ,Шерлок Холмс,Детектив,250,3,0,750.0,Сайт,Олег,5
26,5175,2024-04-26,Дніпро,Шерлок Холмс,Детектив,250,3,0,750.0,Телефон,Софія,4
31,5297,2024-06-20,Львів,Кладовище домашніх тварин,Детектив,270,4,0,1080.0,Мобільний застосунок,Олег,4
34,5158,2024-04-02,Львів,Кладовище домашніх тварин,Детектив,270,2,20,432.0,Сайт,Софія,5
40,5252,2024-06-05,Дніпро,Кладовище домашніх тварин,Детектив,270,1,15,229.5,Телефон,Софія,4
60,5029,2024-01-14,Київ,Шерлок Холмс,Детектив,250,1,0,250.0,Телефон,Ірина,4
64,5214,2024-05-17,Харків,Шерлок Холмс,Детектив,250,3,0,750.0,Сайт,Олег,3
65,5087,2024-02-28,Харків,Шерлок Холмс,Детектив,250,2,0,500.0,Сайт,Віктор,4
94,5355,2024-08-10,Київ,Шерлок Холмс,Детектив,250,1,0,250.0,Мобільний застосунок,Наталя,4
103,5181,2024-04-14,Дніпро,Кладовище домашніх тварин,Детектив,270,1,0,270.0,Сайт,Наталя,4
111,5224,2024-05-24,Київ,Кладовище домашніх тварин,Детектив,270,1,0,270.0,Мобільний застосунок,Олег,3
114,5339,2024-07-02,Харків,Кладовище домашніх тварин,Детектив,270,5,0,1350.0,Мобільний застосунок,Софія,3
119,5113,2024-03-01,Одеса,Кладовище домашніх тварин,Детектив,270,3,0,810.0,Телефон,Ірина,5
126,5178,2024-04-21,Київ,Кладовище домашніх тварин,Детектив,270,1,0,270.0,Телефон,Софія,5
128,5002,2024-01-03,Дніпро,Шерлок Холмс,Детектив,250,2,0,500.0,Телефон,Ірина,4
150,5366,2024-08-20,Харків,Кладовище домашніх тварин,Детектив,270,2,0,540.0,Мобільний застосунок,Віктор,3
152,5166,2024-04-05,Одеса,Шерлок Холмс,Детектив,250,4,0,1000.0,Телефон,Софія,3
157,5251,2024-06-21,Дніпро,Кладовище домашніх тварин,Детектив,270,4,0,1080.0,Сайт,Софія,4
160,5205,2024-05-12,Одеса,Шерлок Холмс,Детектив,250,2,0,500.0,Сайт,Олег,3
166,5108,2024-03-26,Дніпро,Шерлок Холмс,Детектив,250,2,15,425.0,Телефон,Олег,5
170,5367,2024-08-17,Дніпро,Шерлок Холмс,Детектив,250,1,0,250.0,Телефон,Софія,5
173,5094,2024-02-01,Львів,Кладовище домашніх тварин,Детектив,270,2,0,540.0,Мобільний застосунок,Олег,3
179,5379,2024-08-08,Львів,Шерлок Холмс,Детектив,250,2,0,500.0,Мобільний застосунок,Олег,4
196,5338,2024-07-19,Львів,Шерлок Холмс,Детектив,250,1,0,250.0,Мобільний застосунок,Ірина,4
202,5017,2024-01-25,Київ,Кладовище домашніх тварин,Детектив,270,4,5,1026.0,Мобільний застосунок,Віктор,5
219,5292,2024-06-28,Харків,Кладовище домашніх тварин,Детектив,270,3,0,810.0,Мобільний застосунок,Софія,5
223,5134,2024-03-10,Київ,Шерлок Холмс,Детектив,250,1,0,250.0,Мобільний застосунок,Ірина,5
270,5213,2024-05-04,Дніпро,Кладовище домашніх тварин,Детектив,270,2,0,540.0,Сайт,Наталя,5
284,5089,2024-02-18,Харків,Кладовище домашніх тварин,Детектив,270,1,5,256.5,Мобільний застосунок,Софія,5
295,5256,2024-06-14,Львів,Шерлок Холмс,Детектив,250,2,0,500.0,Мобільний застосунок,Софія,4
302,5152,2024-04-10,Київ,Кладовище домашніх тварин,Детектив,270,3,10,729.0,Сайт,Ірина,5
310,5146,2024-03-14,Львів,Шерлок Холмс,Детектив,250,4,0,1000.0,Телефон,Наталя,4
313,5308,2024-07-17,Львів,Шерлок Холмс,Детектив,250,1,0,250.0,Сайт,Ірина,3
330,5227,2024-05-23,Харків,Кладовище домашніх тварин,Детектив,270,1,0,270.0,Сайт,Наталя,5
333,5078,2024-02-05,Львів,Кладовище домашніх тварин,Детектив,270,1,0,270.0,Сайт,Наталя,5
336,5180,2024-04-25,Київ,Шерлок Холмс,Детектив,250,4,0,1000.0,Мобільний застосунок,Віктор,5
349,5196,2024-04-20,Харків,Кладовище домашніх тварин,Детектив,270,3,10,729.0,Мобільний застосунок,Софія,5
365,5176,2024-04-22,Одеса,Кладовище домашніх тварин,Детектив,270,2,0,540.0,Сайт,Олег,5
371,5266,2024-06-12,Одеса,Шерлок Холмс,Детектив,250,1,0,250.0,Телефон,Наталя,5
372,5116,2024-03-14,Одеса,Кладовище домашніх тварин,Детектив,270,1,0,270.0,Телефон,Віктор,5
375,5040,2024-01-25,Київ,Кладовище домашніх тварин,Детектив,270,2,0,540.0,Мобільний застосунок,Софія,5
378,5001,2024-01-08,Київ,Кладовище домашніх тварин,Детектив,270,1,0,270.0,Телефон,Софія,4
383,5220,2024-05-04,Харків,Кладовище домашніх тварин,Детектив,270,3,0,810.0,Телефон,Софія,5
386,5372,2024-08-24,Львів,Кладовище домашніх тварин,Детектив,270,3,15,688.5,Телефон,Олег,4
389,5203,2024-05-21,Харків,Кладовище домашніх тварин,Детектив,270,1,0,270.0,Сайт,Софія,5
391,5085,2024-02-08,Одеса,Шерлок Холмс,Детектив,250,2,5,475.0,Телефон,Софія,3

**Завдання 56.** Виведіть усі замовлення жанру `Дитяча`.

In [ ]:
# Завдання 56:
df[df["genre"]== "Дитяча"]

,order_id,date,city,book_title,genre,unit_price,quantity,discount_pct,total,channel,manager,rating
5,5137,2024-03-06,Харків,Маленький принц,Дитяча,160,2,0,320.0,Телефон,Олег,3
36,5016,2024-01-15,Дніпро,Маленький принц,Дитяча,160,1,0,160.0,Сайт,Ірина,4
39,5101,2024-03-11,Київ,Маленький принц,Дитяча,160,1,0,160.0,Мобільний застосунок,Віктор,4
54,5144,2024-03-25,Львів,Маленький принц,Дитяча,160,1,5,152.0,Телефон,Ірина,5
61,5091,2024-02-01,Одеса,Маленький принц,Дитяча,160,2,0,320.0,Сайт,Віктор,4
71,5278,2024-06-09,Львів,Маленький принц,Дитяча,160,2,15,272.0,Мобільний застосунок,Наталя,5
79,5056,2024-02-11,Дніпро,Маленький принц,Дитяча,160,1,0,160.0,Сайт,Віктор,4
85,5301,2024-07-28,Київ,Маленький принц,Дитяча,160,2,0,320.0,Телефон,Олег,4
90,5011,2024-01-25,Київ,Гаррі Поттер,Дитяча,350,2,10,630.0,Мобільний застосунок,Віктор,3
100,5092,2024-02-09,Одеса,Гаррі Поттер,Дитяча,350,1,0,350.0,Телефон,Ірина,5
118,5241,2024-05-16,Львів,Гаррі Поттер,Дитяча,350,5,0,1750.0,Сайт,Віктор,4
129,5172,2024-04-22,Одеса,Маленький принц,Дитяча,160,4,0,640.0,Телефон,Віктор,3
133,5140,2024-03-23,Одеса,Маленький принц,Дитяча,160,1,15,136.0,Сайт,Віктор,4
134,5119,2024-03-16,Київ,Гаррі Поттер,Дитяча,350,2,0,700.0,Сайт,Наталя,5
144,5084,2024-02-22,Харків,Маленький принц,Дитяча,160,1,0,160.0,Мобільний застосунок,Олег,5
153,5238,2024-05-12,Київ,Маленький принц,Дитяча,160,1,0,160.0,Телефон,Олег,4
167,5259,2024-06-13,Харків,Гаррі Поттер,Дитяча,350,1,0,350.0,Сайт,Олег,5
169,5010,2024-01-08,Харків,Маленький принц,Дитяча,160,2,0,320.0,Мобільний застосунок,Софія,4
172,5099,2024-02-23,Одеса,Гаррі Поттер,Дитяча,350,1,0,350.0,Сайт,Ірина,4
182,5244,2024-05-05,Харків,Гаррі Поттер,Дитяча,350,1,0,350.0,Сайт,Наталя,4
184,5273,2024-06-24,Харків,Маленький принц,Дитяча,160,2,0,320.0,Сайт,Олег,5
185,5391,2024-08-23,Дніпро,Маленький принц,Дитяча,160,2,0,320.0,Мобільний застосунок,Софія,4
186,5066,2024-02-25,Київ,Гаррі Поттер,Дитяча,350,1,0,350.0,Мобільний застосунок,Олег,5
190,5311,2024-07-01,Київ,Маленький принц,Дитяча,160,3,10,432.0,Сайт,Софія,4
205,5383,2024-08-17,Харків,Гаррі Поттер,Дитяча,350,3,15,892.5,Телефон,Віктор,5
213,5200,2024-04-10,Одеса,Маленький принц,Дитяча,160,1,0,160.0,Телефон,Софія,4
228,5323,2024-07-01,Львів,Гаррі Поттер,Дитяча,350,3,0,1050.0,Телефон,Ірина,4
240,5156,2024-04-28,Одеса,Гаррі Поттер,Дитяча,350,1,15,297.5,Телефон,Наталя,4
254,5179,2024-04-06,Одеса,Гаррі Поттер,Дитяча,350,1,0,350.0,Телефон,Софія,4
261,5262,2024-06-02,Дніпро,Гаррі Поттер,Дитяча,350,1,0,350.0,Телефон,Віктор,4
262,5041,2024-01-07,Львів,Маленький принц,Дитяча,160,5,0,800.0,Мобільний застосунок,Ірина,4
263,5159,2024-04-07,Львів,Гаррі Поттер,Дитяча,350,1,5,332.5,Мобільний застосунок,Олег,5
282,5038,2024-01-03,Дніпро,Гаррі Поттер,Дитяча,350,2,0,700.0,Телефон,Софія,4
287,5216,2024-05-08,Київ,Гаррі Поттер,Дитяча,350,1,0,350.0,Телефон,Наталя,3
315,5128,2024-03-14,Харків,Маленький принц,Дитяча,160,1,10,144.0,Телефон,Віктор,3
325,5064,2024-02-02,Харків,Гаррі Поттер,Дитяча,350,3,0,1050.0,Телефон,Ірина,4
328,5045,2024-01-17,Київ,Гаррі Поттер,Дитяча,350,2,10,630.0,Сайт,Віктор,4
329,5112,2024-03-11,Київ,Маленький принц,Дитяча,160,1,0,160.0,Сайт,Олег,5
331,5316,2024-07-21,Дніпро,Маленький принц,Дитяча,160,3,10,432.0,Мобільний застосунок,Ірина,5
340,5313,2024-07-25,Дніпро,Гаррі Поттер,Дитяча,350,2,5,665.0,Мобільний застосунок,Олег,3
341,5368,2024-08-25,Дніпро,Гаррі Поттер,Дитяча,350,1,0,350.0,Сайт,Наталя,5
342,5289,2024-06-10,Дніпро,Маленький принц,Дитяча,160,1,20,128.0,Телефон,Віктор,4
352,5189,2024-04-28,Одеса,Маленький принц,Дитяча,160,1,0,160.0,Сайт,Наталя,4
362,5356,2024-08-20,Київ,Гаррі Поттер,Дитяча,350,2,0,700.0,Сайт,Наталя,4
368,5005,2024-01-03,Одеса,Гаррі Поттер,Дитяча,350,4,0,1400.0,Мобільний застосунок,Софія,4
369,5228,2024-05-02,Одеса,Гаррі Поттер,Дитяча,350,1,0,350.0,Телефон,Віктор,4
393,5341,2024-07-17,Львів,Маленький принц,Дитяча,160,5,20,640.0,Сайт,Софія,5

**Завдання 57.** Виведіть замовлення, де сума (`total`) більша за 500.

In [ ]:
# Завдання 57:
df[df["total"] > 500]

,order_id,date,city,book_title,genre,unit_price,quantity,discount_pct,total,channel,manager,rating
0,5275,2024-06-25,Харків,Sapiens,Наука,410,2,0,820.0,Телефон,Ірина,5
8,5104,2024-03-13,Харків,Квантова фізика,Наука,450,2,5,855.0,Мобільний застосунок,Софія,4
11,5114,2024-03-21,Одеса,Квантова фізика,Наука,450,3,0,1350.0,Сайт,Софія,4
12,5215,2024-05-01,Харків,Сила звички,Бізнес,260,2,0,520.0,Телефон,Наталя,4
14,5295,2024-06-12,Київ,Війна і мир,Історія,380,2,0,760.0,Телефон,Ірина,5
...,...,...,...,...,...,...,...,...,...,...,...,...
393,5341,2024-07-17,Львів,Маленький принц,Дитяча,160,5,20,640.0,Сайт,Софія,5
394,5191,2024-04-05,Львів,Війна і мир,Історія,380,4,0,1520.0,Мобільний застосунок,Олег,4
395,5043,2024-01-22,Львів,Дюна,Фантастика,320,2,0,640.0,Мобільний застосунок,Ірина,3
396,5129,2024-03-21,Харків,Sapiens,Наука,410,5,5,1947.5,Сайт,Олег,5
398,5336,2024-07-26,Львів,Гордість і упередження,Романтика,240,3,0,720.0,Сайт,Ірина,5

**Завдання 58.** Виведіть замовлення, де сума (`total`) більша за 1000.

In [ ]:
# Завдання 58:
df[df["total"] > 1000]

,order_id,date,city,book_title,genre,unit_price,quantity,discount_pct,total,channel,manager,rating
11,5114,2024-03-21,Одеса,Квантова фізика,Наука,450,3,0,1350.0,Сайт,Софія,4
20,5165,2024-04-14,Харків,Дюна,Фантастика,320,5,10,1440.0,Телефон,Віктор,5
31,5297,2024-06-20,Львів,Кладовище домашніх тварин,Детектив,270,4,0,1080.0,Мобільний застосунок,Олег,4
35,5055,2024-02-09,Одеса,Атомні звички,Бізнес,290,4,0,1160.0,Сайт,Ірина,4
42,5130,2024-03-04,Харків,Гордість і упередження,Романтика,240,5,0,1200.0,Сайт,Софія,5
44,5317,2024-07-26,Харків,Атомні звички,Бізнес,290,4,0,1160.0,Мобільний застосунок,Олег,4
55,5125,2024-03-26,Київ,Квантова фізика,Наука,450,3,0,1350.0,Мобільний застосунок,Наталя,4
56,5081,2024-02-01,Львів,Квантова фізика,Наука,450,4,0,1800.0,Сайт,Софія,5
57,5122,2024-03-04,Львів,Сила звички,Бізнес,260,4,0,1040.0,Мобільний застосунок,Наталя,5
58,5277,2024-06-18,Одеса,Атомні звички,Бізнес,290,4,0,1160.0,Телефон,Наталя,4
63,5160,2024-04-28,Львів,Квантова фізика,Наука,450,4,0,1800.0,Телефон,Наталя,5
84,5132,2024-03-23,Київ,Квантова фізика,Наука,450,5,0,2250.0,Мобільний застосунок,Софія,4
88,5013,2024-01-05,Львів,Sapiens,Наука,410,4,0,1640.0,Телефон,Софія,4
92,5400,2024-08-23,Одеса,Дюна,Фантастика,320,5,0,1600.0,Сайт,Наталя,5
102,5209,2024-05-02,Львів,Квантова фізика,Наука,450,4,0,1800.0,Мобільний застосунок,Софія,4
109,5376,2024-08-11,Київ,Квантова фізика,Наука,450,3,0,1350.0,Мобільний застосунок,Віктор,4
114,5339,2024-07-02,Харків,Кладовище домашніх тварин,Детектив,270,5,0,1350.0,Мобільний застосунок,Софія,3
118,5241,2024-05-16,Львів,Гаррі Поттер,Дитяча,350,5,0,1750.0,Сайт,Віктор,4
122,5389,2024-08-28,Харків,Квантова фізика,Наука,450,3,0,1350.0,Сайт,Софія,5
124,5343,2024-07-07,Харків,1984,Фантастика,280,4,0,1120.0,Сайт,Наталя,5
142,5236,2024-05-01,Дніпро,Квантова фізика,Наука,450,3,0,1350.0,Телефон,Віктор,3
143,5247,2024-05-15,Дніпро,1984,Фантастика,280,5,0,1400.0,Мобільний застосунок,Олег,4
157,5251,2024-06-21,Дніпро,Кладовище домашніх тварин,Детектив,270,4,0,1080.0,Сайт,Софія,4
171,5039,2024-01-23,Одеса,Атомні звички,Бізнес,290,4,0,1160.0,Мобільний застосунок,Олег,4
183,5173,2024-04-10,Одеса,Сила звички,Бізнес,260,4,0,1040.0,Сайт,Софія,5
191,5324,2024-07-08,Львів,Війна і мир,Історія,380,5,0,1900.0,Мобільний застосунок,Олег,5
200,5183,2024-04-07,Львів,Sapiens,Наука,410,5,0,2050.0,Сайт,Наталя,4
202,5017,2024-01-25,Київ,Кладовище домашніх тварин,Детектив,270,4,5,1026.0,Мобільний застосунок,Віктор,5
222,5133,2024-03-25,Дніпро,Sapiens,Наука,410,4,0,1640.0,Сайт,Софія,4
228,5323,2024-07-01,Львів,Гаррі Поттер,Дитяча,350,3,0,1050.0,Телефон,Ірина,4
229,5345,2024-07-23,Дніпро,Квантова фізика,Наука,450,3,5,1282.5,Телефон,Наталя,5
231,5004,2024-01-06,Одеса,Квантова фізика,Наука,450,3,5,1282.5,Мобільний застосунок,Олег,5
234,5246,2024-05-17,Харків,Sapiens,Наука,410,5,0,2050.0,Телефон,Ірина,4
249,5365,2024-08-26,Київ,Квантова фізика,Наука,450,5,0,2250.0,Сайт,Олег,4
251,5381,2024-08-06,Харків,Війна і мир,Історія,380,4,15,1292.0,Мобільний застосунок,Олег,5
265,5143,2024-03-26,Одеса,Сила звички,Бізнес,260,4,0,1040.0,Сайт,Олег,4
268,5206,2024-05-08,Львів,Атомні звички,Бізнес,290,4,0,1160.0,Сайт,Наталя,5
269,5364,2024-08-13,Харків,Тіні забутих предків,Історія,220,5,0,1100.0,Телефон,Ірина,4
274,5204,2024-05-13,Одеса,Війна і мир,Історія,380,4,0,1520.0,Сайт,Софія,5
283,5242,2024-05-03,Одеса,1984,Фантастика,280,4,0,1120.0,Телефон,Наталя,5
312,5314,2024-07-19,Одеса,Сила звички,Бізнес,260,4,0,1040.0,Сайт,Наталя,5
317,5142,2024-03-09,Київ,Дюна,Фантастика,320,5,0,1600.0,Телефон,Віктор,3
323,5358,2024-08-20,Одеса,Sapiens,Наука,410,3,10,1107.0,Телефон,Олег,3
325,5064,2024-02-02,Харків,Гаррі Поттер,Дитяча,350,3,0,1050.0,Телефон,Ірина,4
339,5393,2024-08-23,Львів,Війна і мир,Історія,380,3,0,1140.0,Телефон,Віктор,4
345,5074,2024-02-16,Одеса,Сила звички,Бізнес,260,4,0,1040.0,Мобільний застосунок,Віктор,3
348,5069,2024-02-06,Харків,Sapiens,Наука,410,3,0,1230.0,Мобільний застосунок,Наталя,5
360,5377,2024-08-13,Дніпро,Гордість і упередження,Романтика,240,5,0,1200.0,Сайт,Наталя,5
366,5357,2024-08-20,Одеса,Дюна,Фантастика,320,4,0,1280.0,Мобільний застосунок,Наталя,4
368,5005,2024-01-03,Одеса,Гаррі Поттер,Дитяча,350,4,0,1400.0,Мобільний застосунок,Софія,4
394,5191,2024-04-05,Львів,Війна і мир,Історія,380,4,0,1520.0,Мобільний застосунок,Олег,4
396,5129,2024-03-21,Харків,Sapiens,Наука,410,5,5,1947.5,Сайт,Олег,5

**Завдання 59.** Виведіть замовлення, де сума (`total`) менша за 200.

In [ ]:
# Завдання 59:
df[df["total"] < 200]

,order_id,date,city,book_title,genre,unit_price,quantity,discount_pct,total,channel,manager,rating
9,5184,2024-04-24,Львів,Кобзар,Поезія,180,1,0,180.0,Мобільний застосунок,Софія,4
17,5342,2024-07-22,Дніпро,Тіні забутих предків,Історія,220,1,15,187.0,Телефон,Ірина,5
36,5016,2024-01-15,Дніпро,Маленький принц,Дитяча,160,1,0,160.0,Сайт,Ірина,4
39,5101,2024-03-11,Київ,Маленький принц,Дитяча,160,1,0,160.0,Мобільний застосунок,Віктор,4
54,5144,2024-03-25,Львів,Маленький принц,Дитяча,160,1,5,152.0,Телефон,Ірина,5
69,5281,2024-06-03,Харків,Кобзар,Поезія,180,1,15,153.0,Телефон,Наталя,4
79,5056,2024-02-11,Дніпро,Маленький принц,Дитяча,160,1,0,160.0,Сайт,Віктор,4
93,5090,2024-02-03,Харків,Кобзар,Поезія,180,1,0,180.0,Сайт,Віктор,4
98,5151,2024-04-18,Дніпро,Тіні забутих предків,Історія,220,1,10,198.0,Сайт,Ірина,4
101,5019,2024-01-27,Дніпро,Лісова пісня,Поезія,150,1,0,150.0,Сайт,Олег,5
105,5315,2024-07-08,Одеса,Лісова пісня,Поезія,150,1,0,150.0,Сайт,Софія,4
106,5202,2024-05-20,Одеса,Кобзар,Поезія,180,1,10,162.0,Сайт,Софія,5
133,5140,2024-03-23,Одеса,Маленький принц,Дитяча,160,1,15,136.0,Сайт,Віктор,4
144,5084,2024-02-22,Харків,Маленький принц,Дитяча,160,1,0,160.0,Мобільний застосунок,Олег,5
153,5238,2024-05-12,Київ,Маленький принц,Дитяча,160,1,0,160.0,Телефон,Олег,4
168,5318,2024-07-16,Львів,Кобзар,Поезія,180,1,5,171.0,Мобільний застосунок,Олег,4
178,5012,2024-01-19,Одеса,Кобзар,Поезія,180,1,10,162.0,Сайт,Віктор,5
213,5200,2024-04-10,Одеса,Маленький принц,Дитяча,160,1,0,160.0,Телефон,Софія,4
217,5265,2024-06-25,Дніпро,Кобзар,Поезія,180,1,0,180.0,Телефон,Софія,4
224,5285,2024-06-16,Львів,Лісова пісня,Поезія,150,1,0,150.0,Мобільний застосунок,Наталя,4
226,5042,2024-01-15,Одеса,Лісова пісня,Поезія,150,1,0,150.0,Телефон,Софія,5
241,5388,2024-08-03,Київ,Тіні забутих предків,Історія,220,1,10,198.0,Сайт,Олег,4
276,5021,2024-01-27,Львів,Тіні забутих предків,Історія,220,1,15,187.0,Сайт,Олег,5
285,5280,2024-06-13,Харків,Кобзар,Поезія,180,1,0,180.0,Мобільний застосунок,Олег,5
308,5155,2024-04-16,Одеса,Лісова пісня,Поезія,150,1,0,150.0,Сайт,Наталя,5
315,5128,2024-03-14,Харків,Маленький принц,Дитяча,160,1,10,144.0,Телефон,Віктор,3
316,5044,2024-01-09,Львів,Лісова пісня,Поезія,150,1,0,150.0,Телефон,Наталя,4
329,5112,2024-03-11,Київ,Маленький принц,Дитяча,160,1,0,160.0,Сайт,Олег,5
342,5289,2024-06-10,Дніпро,Маленький принц,Дитяча,160,1,20,128.0,Телефон,Віктор,4
350,5071,2024-02-08,Одеса,Кобзар,Поезія,180,1,0,180.0,Телефон,Ірина,4
351,5154,2024-04-23,Харків,Тіні забутих предків,Історія,220,1,15,187.0,Телефон,Олег,5
352,5189,2024-04-28,Одеса,Маленький принц,Дитяча,160,1,0,160.0,Сайт,Наталя,4
379,5049,2024-01-22,Дніпро,Лісова пісня,Поезія,150,1,0,150.0,Мобільний застосунок,Софія,3
385,5359,2024-08-11,Харків,Тіні забутих предків,Історія,220,1,15,187.0,Телефон,Олег,4
390,5027,2024-01-17,Харків,Лісова пісня,Поезія,150,1,0,150.0,Сайт,Софія,4

**Завдання 60.** Виведіть замовлення, де кількість книг (`quantity`) дорівнює 5.

In [ ]:
# Завдання 60:
df[df["quantity"]==5]

,order_id,date,city,book_title,genre,unit_price,quantity,discount_pct,total,channel,manager,rating
20,5165,2024-04-14,Харків,Дюна,Фантастика,320,5,10,1440.0,Телефон,Віктор,5
42,5130,2024-03-04,Харків,Гордість і упередження,Романтика,240,5,0,1200.0,Сайт,Софія,5
84,5132,2024-03-23,Київ,Квантова фізика,Наука,450,5,0,2250.0,Мобільний застосунок,Софія,4
92,5400,2024-08-23,Одеса,Дюна,Фантастика,320,5,0,1600.0,Сайт,Наталя,5
114,5339,2024-07-02,Харків,Кладовище домашніх тварин,Детектив,270,5,0,1350.0,Мобільний застосунок,Софія,3
118,5241,2024-05-16,Львів,Гаррі Поттер,Дитяча,350,5,0,1750.0,Сайт,Віктор,4
143,5247,2024-05-15,Дніпро,1984,Фантастика,280,5,0,1400.0,Мобільний застосунок,Олег,4
191,5324,2024-07-08,Львів,Війна і мир,Історія,380,5,0,1900.0,Мобільний застосунок,Олег,5
200,5183,2024-04-07,Львів,Sapiens,Наука,410,5,0,2050.0,Сайт,Наталя,4
234,5246,2024-05-17,Харків,Sapiens,Наука,410,5,0,2050.0,Телефон,Ірина,4
249,5365,2024-08-26,Київ,Квантова фізика,Наука,450,5,0,2250.0,Сайт,Олег,4
262,5041,2024-01-07,Львів,Маленький принц,Дитяча,160,5,0,800.0,Мобільний застосунок,Ірина,4
269,5364,2024-08-13,Харків,Тіні забутих предків,Історія,220,5,0,1100.0,Телефон,Ірина,4
317,5142,2024-03-09,Київ,Дюна,Фантастика,320,5,0,1600.0,Телефон,Віктор,3
343,5272,2024-06-25,Львів,Кобзар,Поезія,180,5,5,855.0,Телефон,Ірина,5
360,5377,2024-08-13,Дніпро,Гордість і упередження,Романтика,240,5,0,1200.0,Сайт,Наталя,5
393,5341,2024-07-17,Львів,Маленький принц,Дитяча,160,5,20,640.0,Сайт,Софія,5
396,5129,2024-03-21,Харків,Sapiens,Наука,410,5,5,1947.5,Сайт,Олег,5

**Завдання 61.** Виведіть замовлення, де кількість книг більша за 3.

In [ ]:
# Завдання 61:
df[df["quantity"] > 3]

,order_id,date,city,book_title,genre,unit_price,quantity,discount_pct,total,channel,manager,rating
20,5165,2024-04-14,Харків,Дюна,Фантастика,320,5,10,1440.0,Телефон,Віктор,5
22,5025,2024-01-08,Одеса,Тіні забутих предків,Історія,220,4,0,880.0,Сайт,Софія,4
31,5297,2024-06-20,Львів,Кладовище домашніх тварин,Детектив,270,4,0,1080.0,Мобільний застосунок,Олег,4
33,5288,2024-06-10,Київ,1984,Фантастика,280,4,15,952.0,Мобільний застосунок,Софія,5
35,5055,2024-02-09,Одеса,Атомні звички,Бізнес,290,4,0,1160.0,Сайт,Ірина,4
42,5130,2024-03-04,Харків,Гордість і упередження,Романтика,240,5,0,1200.0,Сайт,Софія,5
44,5317,2024-07-26,Харків,Атомні звички,Бізнес,290,4,0,1160.0,Мобільний застосунок,Олег,4
56,5081,2024-02-01,Львів,Квантова фізика,Наука,450,4,0,1800.0,Сайт,Софія,5
57,5122,2024-03-04,Львів,Сила звички,Бізнес,260,4,0,1040.0,Мобільний застосунок,Наталя,5
58,5277,2024-06-18,Одеса,Атомні звички,Бізнес,290,4,0,1160.0,Телефон,Наталя,4
63,5160,2024-04-28,Львів,Квантова фізика,Наука,450,4,0,1800.0,Телефон,Наталя,5
84,5132,2024-03-23,Київ,Квантова фізика,Наука,450,5,0,2250.0,Мобільний застосунок,Софія,4
88,5013,2024-01-05,Львів,Sapiens,Наука,410,4,0,1640.0,Телефон,Софія,4
89,5138,2024-03-15,Харків,Тіні забутих предків,Історія,220,4,0,880.0,Мобільний застосунок,Ірина,5
91,5231,2024-05-06,Харків,Лісова пісня,Поезія,150,4,0,600.0,Мобільний застосунок,Софія,4
92,5400,2024-08-23,Одеса,Дюна,Фантастика,320,5,0,1600.0,Сайт,Наталя,5
102,5209,2024-05-02,Львів,Квантова фізика,Наука,450,4,0,1800.0,Мобільний застосунок,Софія,4
114,5339,2024-07-02,Харків,Кладовище домашніх тварин,Детектив,270,5,0,1350.0,Мобільний застосунок,Софія,3
118,5241,2024-05-16,Львів,Гаррі Поттер,Дитяча,350,5,0,1750.0,Сайт,Віктор,4
124,5343,2024-07-07,Харків,1984,Фантастика,280,4,0,1120.0,Сайт,Наталя,5
129,5172,2024-04-22,Одеса,Маленький принц,Дитяча,160,4,0,640.0,Телефон,Віктор,3
137,5075,2024-02-18,Дніпро,Сила звички,Бізнес,260,4,5,988.0,Телефон,Олег,5
138,5328,2024-07-14,Львів,Гордість і упередження,Романтика,240,4,0,960.0,Мобільний застосунок,Олег,4
143,5247,2024-05-15,Дніпро,1984,Фантастика,280,5,0,1400.0,Мобільний застосунок,Олег,4
152,5166,2024-04-05,Одеса,Шерлок Холмс,Детектив,250,4,0,1000.0,Телефон,Софія,3
157,5251,2024-06-21,Дніпро,Кладовище домашніх тварин,Детектив,270,4,0,1080.0,Сайт,Софія,4
171,5039,2024-01-23,Одеса,Атомні звички,Бізнес,290,4,0,1160.0,Мобільний застосунок,Олег,4
183,5173,2024-04-10,Одеса,Сила звички,Бізнес,260,4,0,1040.0,Сайт,Софія,5
191,5324,2024-07-08,Львів,Війна і мир,Історія,380,5,0,1900.0,Мобільний застосунок,Олег,5
193,5093,2024-02-24,Дніпро,Гордість і упередження,Романтика,240,4,0,960.0,Сайт,Віктор,4
200,5183,2024-04-07,Львів,Sapiens,Наука,410,5,0,2050.0,Сайт,Наталя,4
201,5290,2024-06-15,Київ,Лісова пісня,Поезія,150,4,10,540.0,Мобільний застосунок,Олег,4
202,5017,2024-01-25,Київ,Кладовище домашніх тварин,Детектив,270,4,5,1026.0,Мобільний застосунок,Віктор,5
211,5287,2024-06-27,Київ,Лісова пісня,Поезія,150,4,0,600.0,Мобільний застосунок,Віктор,4
222,5133,2024-03-25,Дніпро,Sapiens,Наука,410,4,0,1640.0,Сайт,Софія,4
233,5348,2024-07-22,Харків,Гордість і упередження,Романтика,240,4,0,960.0,Сайт,Софія,5
234,5246,2024-05-17,Харків,Sapiens,Наука,410,5,0,2050.0,Телефон,Ірина,4
249,5365,2024-08-26,Київ,Квантова фізика,Наука,450,5,0,2250.0,Сайт,Олег,4
251,5381,2024-08-06,Харків,Війна і мир,Історія,380,4,15,1292.0,Мобільний застосунок,Олег,5
262,5041,2024-01-07,Львів,Маленький принц,Дитяча,160,5,0,800.0,Мобільний застосунок,Ірина,4
265,5143,2024-03-26,Одеса,Сила звички,Бізнес,260,4,0,1040.0,Сайт,Олег,4
268,5206,2024-05-08,Львів,Атомні звички,Бізнес,290,4,0,1160.0,Сайт,Наталя,5
269,5364,2024-08-13,Харків,Тіні забутих предків,Історія,220,5,0,1100.0,Телефон,Ірина,4
274,5204,2024-05-13,Одеса,Війна і мир,Історія,380,4,0,1520.0,Сайт,Софія,5
283,5242,2024-05-03,Одеса,1984,Фантастика,280,4,0,1120.0,Телефон,Наталя,5
310,5146,2024-03-14,Львів,Шерлок Холмс,Детектив,250,4,0,1000.0,Телефон,Наталя,4
312,5314,2024-07-19,Одеса,Сила звички,Бізнес,260,4,0,1040.0,Сайт,Наталя,5
317,5142,2024-03-09,Київ,Дюна,Фантастика,320,5,0,1600.0,Телефон,Віктор,3
336,5180,2024-04-25,Київ,Шерлок Холмс,Детектив,250,4,0,1000.0,Мобільний застосунок,Віктор,5
343,5272,2024-06-25,Львів,Кобзар,Поезія,180,5,5,855.0,Телефон,Ірина,5
345,5074,2024-02-16,Одеса,Сила звички,Бізнес,260,4,0,1040.0,Мобільний застосунок,Віктор,3
357,5197,2024-04-02,Дніпро,Гордість і упередження,Романтика,240,4,0,960.0,Телефон,Олег,4
360,5377,2024-08-13,Дніпро,Гордість і упередження,Романтика,240,5,0,1200.0,Сайт,Наталя,5
366,5357,2024-08-20,Одеса,Дюна,Фантастика,320,4,0,1280.0,Мобільний застосунок,Наталя,4
368,5005,2024-01-03,Одеса,Гаррі Поттер,Дитяча,350,4,0,1400.0,Мобільний застосунок,Софія,4
393,5341,2024-07-17,Львів,Маленький принц,Дитяча,160,5,20,640.0,Сайт,Софія,5
394,5191,2024-04-05,Львів,Війна і мир,Історія,380,4,0,1520.0,Мобільний застосунок,Олег,4
396,5129,2024-03-21,Харків,Sapiens,Наука,410,5,5,1947.5,Сайт,Олег,5

**Завдання 62.** Виведіть замовлення з оцінкою (`rating`) 5.

In [ ]:
# Завдання 62:
df[df["rating"]== 5]

,order_id,date,city,book_title,genre,unit_price,quantity,discount_pct,total,channel,manager,rating
0,5275,2024-06-25,Харків,Sapiens,Наука,410,2,0,820.0,Телефон,Ірина,5
1,5386,2024-08-09,Одеса,Гордість і упередження,Романтика,240,2,0,480.0,Телефон,Ірина,5
2,5100,2024-02-21,Харків,Гордість і упередження,Романтика,240,1,15,204.0,Сайт,Ірина,5
14,5295,2024-06-12,Київ,Війна і мир,Історія,380,2,0,760.0,Телефон,Ірина,5
16,5102,2024-03-03,Київ,Шерлок Холмс,Детектив,250,3,0,750.0,Сайт,Олег,5
...,...,...,...,...,...,...,...,...,...,...,...,...
389,5203,2024-05-21,Харків,Кладовище домашніх тварин,Детектив,270,1,0,270.0,Сайт,Софія,5
393,5341,2024-07-17,Львів,Маленький принц,Дитяча,160,5,20,640.0,Сайт,Софія,5
396,5129,2024-03-21,Харків,Sapiens,Наука,410,5,5,1947.5,Сайт,Олег,5
397,5185,2024-04-22,Київ,Війна і мир,Історія,380,1,0,380.0,Мобільний застосунок,Ірина,5
398,5336,2024-07-26,Львів,Гордість і упередження,Романтика,240,3,0,720.0,Сайт,Ірина,5

**Завдання 63.** Виведіть замовлення з оцінкою менше 4.

In [ ]:
# Завдання 63:
df[df["rating"] < 4]

,order_id,date,city,book_title,genre,unit_price,quantity,discount_pct,total,channel,manager,rating
3,5352,2024-08-18,Дніпро,Sapiens,Наука,410,1,0,410.0,Мобільний застосунок,Віктор,3
4,5032,2024-01-27,Київ,Шерлок Холмс,Детектив,250,1,20,200.0,Сайт,Олег,3
5,5137,2024-03-06,Харків,Маленький принц,Дитяча,160,2,0,320.0,Телефон,Олег,3
13,5320,2024-07-21,Харків,Sapiens,Наука,410,1,0,410.0,Мобільний застосунок,Ірина,3
27,5307,2024-07-13,Дніпро,Тіні забутих предків,Історія,220,3,10,594.0,Сайт,Наталя,3
...,...,...,...,...,...,...,...,...,...,...,...,...
382,5399,2024-08-15,Львів,Дюна,Фантастика,320,1,5,304.0,Мобільний застосунок,Віктор,3
391,5085,2024-02-08,Одеса,Шерлок Холмс,Детектив,250,2,5,475.0,Телефон,Софія,3
392,5333,2024-07-05,Дніпро,Сила звички,Бізнес,260,2,0,520.0,Мобільний застосунок,Наталя,3
395,5043,2024-01-22,Львів,Дюна,Фантастика,320,2,0,640.0,Мобільний застосунок,Ірина,3
399,5048,2024-01-14,Одеса,Сила звички,Бізнес,260,1,0,260.0,Мобільний застосунок,Ірина,3

**Завдання 64.** Виведіть замовлення книги `Дюна`.

> 💡 df[df["book_title"] == "Дюна"].

In [ ]:
# Завдання 64:
df[df["book_title"]=="Дюна"]

,order_id,date,city,book_title,genre,unit_price,quantity,discount_pct,total,channel,manager,rating
20,5165,2024-04-14,Харків,Дюна,Фантастика,320,5,10,1440.0,Телефон,Віктор,5
43,5346,2024-07-03,Дніпро,Дюна,Фантастика,320,1,0,320.0,Телефон,Віктор,4
50,5164,2024-04-22,Харків,Дюна,Фантастика,320,2,10,576.0,Телефон,Ірина,4
59,5294,2024-06-25,Одеса,Дюна,Фантастика,320,1,0,320.0,Мобільний застосунок,Софія,4
70,5153,2024-04-04,Дніпро,Дюна,Фантастика,320,1,0,320.0,Сайт,Віктор,4
92,5400,2024-08-23,Одеса,Дюна,Фантастика,320,5,0,1600.0,Сайт,Наталя,5
136,5334,2024-07-20,Харків,Дюна,Фантастика,320,2,0,640.0,Сайт,Ірина,5
139,5353,2024-08-03,Дніпро,Дюна,Фантастика,320,1,0,320.0,Сайт,Софія,5
147,5385,2024-08-06,Дніпро,Дюна,Фантастика,320,1,0,320.0,Телефон,Віктор,5
156,5221,2024-05-23,Харків,Дюна,Фантастика,320,2,0,640.0,Сайт,Софія,3
238,5274,2024-06-07,Одеса,Дюна,Фантастика,320,2,0,640.0,Мобільний застосунок,Олег,3
243,5030,2024-01-28,Львів,Дюна,Фантастика,320,1,0,320.0,Сайт,Софія,3
245,5237,2024-05-21,Харків,Дюна,Фантастика,320,1,0,320.0,Телефон,Ірина,4
267,5396,2024-08-03,Харків,Дюна,Фантастика,320,3,10,864.0,Телефон,Наталя,5
279,5008,2024-01-03,Київ,Дюна,Фантастика,320,2,5,608.0,Мобільний застосунок,Наталя,5
303,5201,2024-05-03,Дніпро,Дюна,Фантастика,320,3,0,960.0,Телефон,Віктор,4
311,5312,2024-07-28,Київ,Дюна,Фантастика,320,1,0,320.0,Мобільний застосунок,Віктор,3
314,5284,2024-06-16,Львів,Дюна,Фантастика,320,1,0,320.0,Сайт,Софія,3
317,5142,2024-03-09,Київ,Дюна,Фантастика,320,5,0,1600.0,Телефон,Віктор,3
344,5036,2024-01-28,Київ,Дюна,Фантастика,320,1,0,320.0,Телефон,Ірина,4
366,5357,2024-08-20,Одеса,Дюна,Фантастика,320,4,0,1280.0,Мобільний застосунок,Наталя,4
367,5369,2024-08-03,Львів,Дюна,Фантастика,320,2,0,640.0,Мобільний застосунок,Наталя,3
382,5399,2024-08-15,Львів,Дюна,Фантастика,320,1,5,304.0,Мобільний застосунок,Віктор,3
387,5157,2024-04-04,Харків,Дюна,Фантастика,320,1,0,320.0,Сайт,Олег,5
395,5043,2024-01-22,Львів,Дюна,Фантастика,320,2,0,640.0,Мобільний застосунок,Ірина,3

**Завдання 65.** Виведіть замовлення книги `1984`.

In [ ]:
# Завдання 65:
df[df["book_title"]== "1984"]

,order_id,date,city,book_title,genre,unit_price,quantity,discount_pct,total,channel,manager,rating
21,5194,2024-04-21,Одеса,1984,Фантастика,280,1,0,280.0,Телефон,Ірина,4
33,5288,2024-06-10,Київ,1984,Фантастика,280,4,15,952.0,Мобільний застосунок,Софія,5
37,5382,2024-08-02,Київ,1984,Фантастика,280,1,0,280.0,Мобільний застосунок,Олег,5
75,5344,2024-07-28,Дніпро,1984,Фантастика,280,2,0,560.0,Мобільний застосунок,Віктор,4
76,5283,2024-06-08,Дніпро,1984,Фантастика,280,1,0,280.0,Сайт,Олег,4
78,5390,2024-08-26,Одеса,1984,Фантастика,280,3,5,798.0,Телефон,Наталя,3
123,5234,2024-05-02,Одеса,1984,Фантастика,280,2,0,560.0,Телефон,Віктор,5
124,5343,2024-07-07,Харків,1984,Фантастика,280,4,0,1120.0,Сайт,Наталя,5
131,5051,2024-02-14,Львів,1984,Фантастика,280,3,0,840.0,Мобільний застосунок,Олег,5
143,5247,2024-05-15,Дніпро,1984,Фантастика,280,5,0,1400.0,Мобільний застосунок,Олег,4
148,5018,2024-01-24,Дніпро,1984,Фантастика,280,2,15,476.0,Сайт,Софія,4
161,5082,2024-02-04,Львів,1984,Фантастика,280,1,0,280.0,Мобільний застосунок,Наталя,5
214,5192,2024-04-21,Харків,1984,Фантастика,280,2,5,532.0,Мобільний застосунок,Софія,3
218,5067,2024-02-15,Львів,1984,Фантастика,280,3,0,840.0,Сайт,Віктор,3
246,5023,2024-01-06,Дніпро,1984,Фантастика,280,2,15,476.0,Мобільний застосунок,Олег,4
271,5257,2024-06-24,Одеса,1984,Фантастика,280,1,0,280.0,Мобільний застосунок,Олег,5
280,5035,2024-01-02,Дніпро,1984,Фантастика,280,1,0,280.0,Сайт,Наталя,5
283,5242,2024-05-03,Одеса,1984,Фантастика,280,4,0,1120.0,Телефон,Наталя,5
296,5124,2024-03-17,Львів,1984,Фантастика,280,1,15,238.0,Сайт,Наталя,5
301,5028,2024-01-19,Харків,1984,Фантастика,280,2,10,504.0,Мобільний застосунок,Олег,4
326,5072,2024-02-05,Київ,1984,Фантастика,280,1,0,280.0,Мобільний застосунок,Віктор,5
354,5363,2024-08-22,Харків,1984,Фантастика,280,2,0,560.0,Мобільний застосунок,Ірина,4
374,5068,2024-02-18,Харків,1984,Фантастика,280,3,0,840.0,Телефон,Софія,5
377,5110,2024-03-27,Одеса,1984,Фантастика,280,3,0,840.0,Мобільний застосунок,Ірина,5

**Завдання 66.** Виведіть замовлення, оформлені через канал `Сайт`.

In [ ]:
# Завдання 66:
df[df["channel"]=="Сайт"]

,order_id,date,city,book_title,genre,unit_price,quantity,discount_pct,total,channel,manager,rating
2,5100,2024-02-21,Харків,Гордість і упередження,Романтика,240,1,15,204.0,Сайт,Ірина,5
4,5032,2024-01-27,Київ,Шерлок Холмс,Детектив,250,1,20,200.0,Сайт,Олег,3
11,5114,2024-03-21,Одеса,Квантова фізика,Наука,450,3,0,1350.0,Сайт,Софія,4
16,5102,2024-03-03,Київ,Шерлок Холмс,Детектив,250,3,0,750.0,Сайт,Олег,5
22,5025,2024-01-08,Одеса,Тіні забутих предків,Історія,220,4,0,880.0,Сайт,Софія,4
...,...,...,...,...,...,...,...,...,...,...,...,...
389,5203,2024-05-21,Харків,Кладовище домашніх тварин,Детектив,270,1,0,270.0,Сайт,Софія,5
390,5027,2024-01-17,Харків,Лісова пісня,Поезія,150,1,0,150.0,Сайт,Софія,4
393,5341,2024-07-17,Львів,Маленький принц,Дитяча,160,5,20,640.0,Сайт,Софія,5
396,5129,2024-03-21,Харків,Sapiens,Наука,410,5,5,1947.5,Сайт,Олег,5
398,5336,2024-07-26,Львів,Гордість і упередження,Романтика,240,3,0,720.0,Сайт,Ірина,5

**Завдання 67.** Виведіть замовлення, оформлені через канал `Телефон`.

In [ ]:
# Завдання 67:
df[df["channel"]=="Телефон"]

,order_id,date,city,book_title,genre,unit_price,quantity,discount_pct,total,channel,manager,rating
0,5275,2024-06-25,Харків,Sapiens,Наука,410,2,0,820.0,Телефон,Ірина,5
1,5386,2024-08-09,Одеса,Гордість і упередження,Романтика,240,2,0,480.0,Телефон,Ірина,5
5,5137,2024-03-06,Харків,Маленький принц,Дитяча,160,2,0,320.0,Телефон,Олег,3
6,5022,2024-01-24,Київ,Лісова пісня,Поезія,150,2,0,300.0,Телефон,Олег,4
10,5208,2024-05-13,Львів,Лісова пісня,Поезія,150,3,0,450.0,Телефон,Софія,4
...,...,...,...,...,...,...,...,...,...,...,...,...
384,5120,2024-03-23,Київ,Гордість і упередження,Романтика,240,1,0,240.0,Телефон,Софія,4
385,5359,2024-08-11,Харків,Тіні забутих предків,Історія,220,1,15,187.0,Телефон,Олег,4
386,5372,2024-08-24,Львів,Кладовище домашніх тварин,Детектив,270,3,15,688.5,Телефон,Олег,4
388,5321,2024-07-09,Дніпро,Гордість і упередження,Романтика,240,2,0,480.0,Телефон,Ірина,4
391,5085,2024-02-08,Одеса,Шерлок Холмс,Детектив,250,2,5,475.0,Телефон,Софія,3

**Завдання 68.** Виведіть замовлення менеджера `Ірина`.

In [ ]:
# Завдання 68:
# Замовлення менеджера Ірина
df[df["manager"] == "Ірина"]

,order_id,date,city,book_title,genre,unit_price,quantity,discount_pct,total,channel,manager,rating
0,5275,2024-06-25,Харків,Sapiens,Наука,410,2,0,820.0,Телефон,Ірина,5
1,5386,2024-08-09,Одеса,Гордість і упередження,Романтика,240,2,0,480.0,Телефон,Ірина,5
2,5100,2024-02-21,Харків,Гордість і упередження,Романтика,240,1,15,204.0,Сайт,Ірина,5
13,5320,2024-07-21,Харків,Sapiens,Наука,410,1,0,410.0,Мобільний застосунок,Ірина,3
14,5295,2024-06-12,Київ,Війна і мир,Історія,380,2,0,760.0,Телефон,Ірина,5
...,...,...,...,...,...,...,...,...,...,...,...,...
388,5321,2024-07-09,Дніпро,Гордість і упередження,Романтика,240,2,0,480.0,Телефон,Ірина,4
395,5043,2024-01-22,Львів,Дюна,Фантастика,320,2,0,640.0,Мобільний застосунок,Ірина,3
397,5185,2024-04-22,Київ,Війна і мир,Історія,380,1,0,380.0,Мобільний застосунок,Ірина,5
398,5336,2024-07-26,Львів,Гордість і упередження,Романтика,240,3,0,720.0,Сайт,Ірина,5
399,5048,2024-01-14,Одеса,Сила звички,Бізнес,260,1,0,260.0,Мобільний застосунок,Ірина,3

**Завдання 69.** Виведіть замовлення, де була застосована знижка (`discount_pct` більше 0).

In [ ]:
# Завдання 69:
df[df["discount_pct"] > 0]

,order_id,date,city,book_title,genre,unit_price,quantity,discount_pct,total,channel,manager,rating
2,5100,2024-02-21,Харків,Гордість і упередження,Романтика,240,1,15,204.0,Сайт,Ірина,5
4,5032,2024-01-27,Київ,Шерлок Холмс,Детектив,250,1,20,200.0,Сайт,Олег,3
7,5139,2024-03-22,Київ,Лісова пісня,Поезія,150,3,10,405.0,Мобільний застосунок,Наталя,4
8,5104,2024-03-13,Харків,Квантова фізика,Наука,450,2,5,855.0,Мобільний застосунок,Софія,4
17,5342,2024-07-22,Дніпро,Тіні забутих предків,Історія,220,1,15,187.0,Телефон,Ірина,5
...,...,...,...,...,...,...,...,...,...,...,...,...
385,5359,2024-08-11,Харків,Тіні забутих предків,Історія,220,1,15,187.0,Телефон,Олег,4
386,5372,2024-08-24,Львів,Кладовище домашніх тварин,Детектив,270,3,15,688.5,Телефон,Олег,4
391,5085,2024-02-08,Одеса,Шерлок Холмс,Детектив,250,2,5,475.0,Телефон,Софія,3
393,5341,2024-07-17,Львів,Маленький принц,Дитяча,160,5,20,640.0,Сайт,Софія,5
396,5129,2024-03-21,Харків,Sapiens,Наука,410,5,5,1947.5,Сайт,Олег,5

**Завдання 70.** Виведіть замовлення, де ціна книги (`unit_price`) дорівнює або більша за 400.

In [ ]:
# Завдання 70:
df[df["unit_price"] >= 400]

,order_id,date,city,book_title,genre,unit_price,quantity,discount_pct,total,channel,manager,rating
0,5275,2024-06-25,Харків,Sapiens,Наука,410,2,0,820.0,Телефон,Ірина,5
3,5352,2024-08-18,Дніпро,Sapiens,Наука,410,1,0,410.0,Мобільний застосунок,Віктор,3
8,5104,2024-03-13,Харків,Квантова фізика,Наука,450,2,5,855.0,Мобільний застосунок,Софія,4
11,5114,2024-03-21,Одеса,Квантова фізика,Наука,450,3,0,1350.0,Сайт,Софія,4
13,5320,2024-07-21,Харків,Sapiens,Наука,410,1,0,410.0,Мобільний застосунок,Ірина,3
...,...,...,...,...,...,...,...,...,...,...,...,...
348,5069,2024-02-06,Харків,Sapiens,Наука,410,3,0,1230.0,Мобільний застосунок,Наталя,5
353,5161,2024-04-01,Одеса,Квантова фізика,Наука,450,1,0,450.0,Сайт,Софія,3
363,5217,2024-05-27,Львів,Квантова фізика,Наука,450,1,0,450.0,Телефон,Віктор,4
373,5304,2024-07-07,Київ,Sapiens,Наука,410,1,0,410.0,Мобільний застосунок,Наталя,5
396,5129,2024-03-21,Харків,Sapiens,Наука,410,5,5,1947.5,Сайт,Олег,5

## Розділ 5. Фільтрація + підрахунок (завдання 71-80)

Поєднуємо фільтр з `len()` або агрегатами, щоб одразу отримати число.

**Завдання 71.** Скільки замовлень з міста Київ?

> 💡 Оберніть фільтр у len(): len(df[df["city"] == "Київ"]).

In [ ]:
# Завдання 71:

**Завдання 72.** Скільки замовлень жанру `Наука`?

In [ ]:
# Завдання 72:

**Завдання 73.** Скільки замовлень із сумою більше 800?

In [ ]:
# Завдання 73:

**Завдання 74.** Яка загальна виручка (`total`) з міста Львів?

> 💡 Відфільтруйте Львів, потім візьміть ["total"].sum().

In [ ]:
# Завдання 74:

**Завдання 75.** Яка загальна виручка з жанру `Бізнес`?

In [ ]:
# Завдання 75:

**Завдання 76.** Яка середня сума замовлення в місті Одеса?

In [ ]:
# Завдання 76:

**Завдання 77.** Скільки замовлень з оцінкою 5?

In [ ]:
# Завдання 77:

**Завдання 78.** Скільки книг (`quantity`) було продано в місті Харків?

> 💡 Фільтр + ["quantity"].sum().

In [ ]:
# Завдання 78:

**Завдання 79.** Яка середня оцінка замовлень через канал `Мобільний застосунок`?

In [ ]:
# Завдання 79:

**Завдання 80.** Скільки замовлень оформила менеджер `Софія`?

In [ ]:
# Завдання 80:

## Розділ 6. Фільтрація — кілька умов (завдання 81-95)

Поєднуємо умови через `&` (І) та `|` (АБО). Кожну умову беремо в дужки!
Наприклад: `df[(df["city"] == "Київ") & (df["total"] > 500)]`.

**Завдання 81.** Виведіть замовлення з Києва, де сума більша за 500.

> 💡 Дві умови через &, кожна в дужках.

In [ ]:
# Завдання 81:

**Завдання 82.** Виведіть замовлення жанру `Фантастика` із сумою більше 600.

In [ ]:
# Завдання 82:

**Завдання 83.** Виведіть замовлення з Львова з оцінкою 5.

In [ ]:
# Завдання 83:

**Завдання 84.** Виведіть замовлення, де жанр `Детектив` АБО `Фантастика`.

> 💡 Використайте | (АБО).

In [ ]:
# Завдання 84:

**Завдання 85.** Виведіть замовлення з міст Київ АБО Одеса.

In [ ]:
# Завдання 85:

**Завдання 86.** Виведіть замовлення, де кількість книг більша за 2 І застосована знижка (>0).

In [ ]:
# Завдання 86:

**Завдання 87.** Виведіть замовлення з Харкова через канал `Сайт`.

In [ ]:
# Завдання 87:

**Завдання 88.** Виведіть замовлення менеджера `Олег` із сумою більше 700.

In [ ]:
# Завдання 88:

**Завдання 89.** Виведіть замовлення книги `Гаррі Поттер` з оцінкою 5.

In [ ]:
# Завдання 89:

**Завдання 90.** Виведіть замовлення, де ціна (`unit_price`) між 200 і 300 (більше або дорівнює 200 І менше або дорівнює 300).

In [ ]:
# Завдання 90:

**Завдання 91.** Виведіть замовлення з оцінкою 4 АБО 5.

In [ ]:
# Завдання 91:

**Завдання 92.** Виведіть замовлення жанру `Наука` з міста Київ.

In [ ]:
# Завдання 92:

**Завдання 93.** Виведіть замовлення зі знижкою 10% або 15%.

> 💡 Дві умови через |.

In [ ]:
# Завдання 93:

**Завдання 94.** Виведіть замовлення через канал `Телефон` із сумою менше 300.

In [ ]:
# Завдання 94:

**Завдання 95.** Скільки замовлень з Києва із сумою більше 500?

> 💡 Поєднайте фільтр з кількох умов і len().

In [ ]:
# Завдання 95:

## Розділ 7. Створення нових стовпців (завдання 96-105)

Новий стовпець: `df["нова_назва"] = вираз`. Операції застосовуються до всього стовпця одразу.

**Завдання 96.** Створіть стовпець `full_price`, що дорівнює `unit_price` × `quantity` (ціна без знижки).

In [ ]:
# Завдання 96:

**Завдання 97.** Створіть стовпець `discount_amount` = `full_price` − `total` (скільки зекономлено на знижці).

> 💡 Спочатку виконайте попереднє завдання, щоб був стовпець full_price.

In [ ]:
# Завдання 97:

**Завдання 98.** Створіть стовпець `price_with_tax`, що дорівнює `total`, збільшеному на 5% (помножте на 1.05).

In [ ]:
# Завдання 98:

**Завдання 99.** Створіть стовпець `is_big`, який дорівнює `True`, якщо `total` більше 700.

> 💡 df["is_big"] = df["total"] > 700.

In [ ]:
# Завдання 99:

**Завдання 100.** Створіть стовпець `is_discounted`, який дорівнює `True`, якщо `discount_pct` більше 0.

In [ ]:
# Завдання 100:

**Завдання 101.** Створіть стовпець `total_uah_rounded` — суму замовлення, округлену до цілого.

> 💡 Використайте .round() на стовпці.

In [ ]:
# Завдання 101:

**Завдання 102.** Створіть стовпець `books_per_order`, що дублює `quantity` (просто скопіюйте стовпець у новий).

In [ ]:
# Завдання 102:

**Завдання 103.** Створіть стовпець `high_rating`, який дорівнює `True`, якщо оцінка дорівнює 5.

In [ ]:
# Завдання 103:

**Завдання 104.** Створіть стовпець `revenue_per_book` = `total` ÷ `quantity` (середня ціна за книгу в замовленні).

In [ ]:
# Завдання 104:

**Завдання 105.** Створіть стовпець `city_upper`, де назва міста написана великими літерами.

> 💡 Для тексту: df["city"].str.upper().

In [ ]:
# Завдання 105:

## Розділ 8. Сортування (завдання 106-112)

`df.sort_values("стовпець")` — за зростанням, `ascending=False` — за спаданням.

**Завдання 106.** Відсортуйте таблицю за сумою (`total`) від найбільшої до найменшої. Виведіть перші 5.

> 💡 sort_values з ascending=False.

In [ ]:
# Завдання 106:

**Завдання 107.** Відсортуйте таблицю за сумою (`total`) від найменшої до найбільшої. Виведіть перші 5.

In [ ]:
# Завдання 107:

**Завдання 108.** Відсортуйте таблицю за ціною книги (`unit_price`) за спаданням. Виведіть перші 10.

In [ ]:
# Завдання 108:

**Завдання 109.** Відсортуйте таблицю за кількістю книг (`quantity`) за спаданням. Виведіть перші 5.

In [ ]:
# Завдання 109:

**Завдання 110.** Відсортуйте таблицю за оцінкою (`rating`) за зростанням. Виведіть перші 5.

In [ ]:
# Завдання 110:

**Завдання 111.** Знайдіть 3 найдорожчі замовлення (за `total`).

> 💡 Відсортуйте за спаданням і візьміть head(3).

In [ ]:
# Завдання 111:

**Завдання 112.** Знайдіть 3 найдешевші замовлення (за `total`).

In [ ]:
# Завдання 112:

## Розділ 9. Групування — groupby (завдання 113-120)

Схема: `df.groupby("стовпець")["що_рахувати"].агрегат()`.

**Завдання 113.** Порахуйте загальну виручку (`total`) по кожному місту.

> 💡 df.groupby("city")["total"].sum().

In [ ]:
# Завдання 113:

**Завдання 114.** Порахуйте середню суму замовлення по кожному жанру.

> 💡 groupby genre, потім mean().

In [ ]:
# Завдання 114:

**Завдання 115.** Порахуйте кількість замовлень по кожному менеджеру.

> 💡 groupby manager, потім count() на якомусь стовпці.

In [ ]:
# Завдання 115:

**Завдання 116.** Порахуйте загальну кількість проданих книг (`quantity`) по кожному жанру.

In [ ]:
# Завдання 116:

**Завдання 117.** Порахуйте середню оцінку (`rating`) по кожному каналу (`channel`).

In [ ]:
# Завдання 117:

**Завдання 118.** Знайдіть загальну виручку по жанрах і відсортуйте за спаданням.

> 💡 Після groupby().sum() додайте .sort_values(ascending=False).

In [ ]:
# Завдання 118:

**Завдання 119.** Порахуйте середню, мінімальну і максимальну суму замовлення по містах.

> 💡 Використайте .agg(["mean", "min", "max"]).

In [ ]:
# Завдання 119:

**Завдання 120.** Порахуйте загальну виручку по двох стовпцях одночасно: місто і жанр.

> 💡 groupby(["city", "genre"]).

In [ ]:
# Завдання 120:

---

# 🎉 Готово!

Якщо ви пройшли всі 120 завдань — вітаємо! Ви відпрацювали весь базовий синтаксис pandas:

- ✅ Перший погляд на дані (`head`, `tail`, `shape`, `info`, `describe`)
- ✅ Вибір стовпців
- ✅ Агрегати (`sum`, `mean`, `max`, `min`, `unique`, `value_counts`, `nunique`)
- ✅ Фільтрація (одна умова та кілька умов)
- ✅ Створення нових стовпців
- ✅ Сортування
- ✅ Групування (`groupby`)

### Порада
Найкращий спосіб закріпити — повернутись через кілька днів і пройти завдання ще раз, не підглядаючи. Те, що спочатку вимагало роздумів, стане автоматичним.

**Так тримати! 🐼**